# Generated by Django 4.2.29 on 2026-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='retry_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='retry_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jdsession',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
