# Generated by Django 4.2.29 on 2026-04-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_attempt_retry_answer_attempt_retry_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdsession',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
