# Generated by Django 4.2.29 on 2026-04-06 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0003_jdsession_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField(choices=[(10, '10 Minutes'), (20, '20 Minutes'), (30, '30 Minutes'), (40, '40 Minutes'), (60, '1 Hour')], default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('filler_words', models.TextField(blank=True)),
                ('communication_tips', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('video_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_attempts', to='interviews.videosession')),
            ],
        ),
    ]
